# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@2.0.2
jobs:
  build:  
    working_directory: ~/angular-toolkit
    docker:
      - image: circleci/node:14.15-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  test:
    docker:
      - image: circleci/node:14.15-browsers
    steps:
      - run: npm install
      - run: npm run build

  # "build":
  #    docker:
  #     - image: circleci/node:8-browsers
  #   steps:
  #     - checkout
  #     - node/install
  #     - run npm run build
  # "test":
  #   docker:
  #     - image: circleci/node:8-browsers
  #   steps:
  #     - checkout
  #     - node/install
  #     - run npm run test 
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  angular-toolkit-ci:
    jobs:
      - build
      - test
   
